INSERT INTO CATEGORIE  VALUES (1, 'LAZER');
INSERT INTO CATEGORIE  VALUES (2, 'FARMACIA');

INSERT INTO PEOPLE  VALUES (1, 'PAULO RODOLFO');
INSERT INTO PEOPLE  VALUES (2, 'LUCIANA GOMES');
INSERT INTO PEOPLE  VALUES (3, 'PAULO SERGIO');

INSERT INTO ADDRESS VALUES (1, 'LUPIONOPOLIS', 'CASA', 'CENTRO', 992, 'RUA PEREIRA LIRA', 'PR', '86635-000');
INSERT INTO ADDRESS VALUES (2, 'LUPIONOPOLIS', 'CASA', 'CENTRO', 992, 'RUA PEREIRA LIRA', 'PR', '86635-000');
INSERT INTO ADDRESS VALUES (3, 'LUPIONOPOLIS', 'CASA', 'CENTRO', 992, 'RUA PEREIRA LIRA', 'PR', '86635-000');


